describe('formulario', () => {
  it('success', () => {
    cy.visit('http://localhost:3000')
    cy.get('#email').type('4dt@gmail.com')
    cy.get('#password').type('4DT')
    cy.contains('button', 'Entrar').click()
    cy.contains('h4', 'Formulários').click()
    cy.get('#name').type('Thiago Menezes')
    cy.get('#email').type('thiagos@gmail.com')
    cy.get('#phone').type('11999999999').should('have.value', '(11) 99999-9999')
    cy.get('#consultancyType').select('Individual')
    cy.contains('span', 'Pessoa Física').click()
    cy.contains('span', 'Pessoa Jurídica').should('be.not.checked')
    cy.get('#document').type('12345678900').should('have.value', '123.456.789-00')
    cy.contains('label', 'Instagram').find('input').check().should('be.checked')
    cy.get('input[type="file"]').selectFile('cypress/fixtures/a9e79599e66427f00fe83ad66c199c91.jpg', { force: true })
    cy.get('#details').type('Gostaria de saber mais sobre os serviços de consultoria individual. Estou interessado em entender como a consultoria pode me ajudar a alcançar meus objetivos pessoais e profissionais. Por favor, entre em contato comigo para discutir mais detalhes e agendar uma consulta. Obrigado!')
    cy.get('#technologies').type('JavaScript {enter}').should('be.visible', 'JavaScript')
    cy.contains('label', 'Li e aceito os').find('input').check().should('be.checked')
    cy.contains('button', 'Enviar formulário').click()
    cy.wait(3000)
    cy.contains('button', 'Fechar').should('be.visible').click()
    cy.contains('a', 'Voltar para o Dashboard').should('be.visible').click()
  })
  it('should show error message', () => {
    cy.visit('http://localhost:3000')
    cy.get('#email').type('4dt@gmail.com')
    cy.get('#password').type('4DT')
    cy.contains('button', 'Entrar').click()
    cy.contains('h4', 'Formulários').click()
    cy.contains('button', 'Enviar formulário').click()
    cy.wait(3000)
    cy.get('p').should('have.css', 'color', 'rgb(248, 113, 113)')

  }
)
})